package com.example.telemedicine.domain;

public enum SymptomType {
    FEVER,
    MUSCLE_WEAKNESS,
    SLURRED_SPEECH,
    BREATHING_DIFFICULTY,
    TREMORS,
    SWALLOWING_DIFFICULTY,
    SKELETAL_DEFORMITIES,
    MUSCLE_ATROPHY,
    FASCICULATIONS,
    CARDIAC_ABNORMALITIES,
    RESPIRATORY_FAILURE,
    DECREASED_MOTOR_ACTIVITY,
    JOINT_CONTRACTURES,
    ABDOMINAL_DISTENTION,
    HAND_TREMORS,
    FATIGUE,
    POOR_FEEDING,
    SPEECH_DELAY,
    SLEEP_DISTURBANCES,
    AUTONOMIC_DYSFUNCTION,
    FACIAL_WEAKNESS,
    POSTURAL_INSTABILITY,
    HEAD_CONTROL_DIFFICULTY,
    LOSS_OF_MOTOR_SKILLS
}
